# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joy', '0002_auto_20160406_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fb_userid',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
