# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joy', '0003_user_fb_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('name', models.CharField(default='tic tac', max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nickname',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
