# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joy', '0005_auto_20160407_0559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ('date_joined',)},
        ),
    ]
